version: "3.7"
services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/shopping
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./public:/app/public
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=shopping
    volumes:
      - mongo-prod:/data/db
      - ./DbInit:/docker-entrypoint-initdb.d
volumes:
  mongo-prod:
